# Generated by Django 3.1 on 2021-01-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users',
        ),
    ]
